# Generated by Django 2.2 on 2019-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(default='', max_length=250)),
                ('Phone_no', models.IntegerField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.CharField(default='', max_length=250)),
                ('Category_id', models.ForeignKey(on_delete='CASCADE', to='design.category')),
                ('Supplier_id', models.ForeignKey(on_delete='CASCADE', to='design.Supplier')),
            ],
        ),
    ]
