# Generated by Django 2.2 on 2019-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='', max_length=250)),
                ('quantity', models.CharField(default='', max_length=250)),
                ('Price', models.CharField(default='', max_length=250)),
                ('total', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
