# Generated by Django 2.2 on 2019-07-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
