# Generated by Django 2.2 on 2019-07-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Supplier',
        ),
    ]
