# Generated by Django 2.2 on 2019-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20190721_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=1),
        ),
    ]
