# Generated by Django 2.2 on 2019-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_auto_20190721_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=''),
        ),
    ]
