# Generated by Django 2.2 on 2019-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20190721_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_Id',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
