# Generated by Django 2.2 on 2019-07-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='Name',
        ),
    ]
