# Generated by Django 2.2 on 2019-07-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20190721_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='c_Name',
        ),
    ]
