# Generated by Django 2.2 on 2019-07-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0021_auto_20190721_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='c_Name',
        ),
    ]
