# Generated by Django 2.2 on 2019-07-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_remove_feedback_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='c_Name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
